// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6yBE_I9svAjvzoKDac18fP3BhUNNK1yU',
    appId: '1:522010967499:web:b98292851b90f1836a4a4e',
    messagingSenderId: '522010967499',
    projectId: 'chess-bf764',
    authDomain: 'chess-bf764.firebaseapp.com',
    databaseURL: 'https://chess-bf764-default-rtdb.firebaseio.com',
    storageBucket: 'chess-bf764.appspot.com',
    measurementId: 'G-WMNESRGMDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChdfjTL_RIs-LnB0iW999jtHN27RWmKpA',
    appId: '1:522010967499:android:5ecb2f7419c13cee6a4a4e',
    messagingSenderId: '522010967499',
    projectId: 'chess-bf764',
    databaseURL: 'https://chess-bf764-default-rtdb.firebaseio.com',
    storageBucket: 'chess-bf764.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjOLV7UiL5jvklJ0yYSSlpu1cFm9-hprY',
    appId: '1:522010967499:ios:aabb3761792954d46a4a4e',
    messagingSenderId: '522010967499',
    projectId: 'chess-bf764',
    databaseURL: 'https://chess-bf764-default-rtdb.firebaseio.com',
    storageBucket: 'chess-bf764.appspot.com',
    iosBundleId: 'com.example.chess',
  );
}
